"""Unified TTS gateway: voice cloning + generation across Qwen3-TTS and OmniVoice.

A single port you can SSH port-forward. Workflow is cloning-first:

  1. POST /voices  (upload a reference clip + its transcript)  -> voice_id
  2. POST /tts     ({text, voice_id, model})                   -> WAV bytes

A voice_id is just a stored reference clip, so the SAME id works with either
model at generation time.

Endpoints:
  GET    /                 usage
  GET    /health           gateway + worker readiness
  POST   /voices           multipart upload -> register a voice (clone source)
  GET    /voices           list registered voices
  GET    /voices/{id}      voice detail
  DELETE /voices/{id}      remove a voice
  POST   /tts              generate speech (JSON) -> audio/wav
"""

from __future__ import annotations

import json
import os
import time
import uuid
from pathlib import Path

import httpx
import soundfile as sf
import uvicorn
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel

VOICES_DIR = Path(os.environ.get("TTS_VOICES_DIR", "/root/tts_voices"))
VOICES_DIR.mkdir(parents=True, exist_ok=True)

WORKERS = {
    "qwen3": os.environ.get("QWEN3_WORKER_URL", "http://127.0.0.1:8101"),
    "omnivoice": os.environ.get("OMNIVOICE_WORKER_URL", "http://127.0.0.1:8102"),
}
DEFAULT_MODEL = "qwen3"
REQUEST_TIMEOUT = float(os.environ.get("TTS_REQUEST_TIMEOUT", "600"))

app = FastAPI(title="vllm-omni TTS gateway")


# ---- voice registry ----------------------------------------------------------
def _voice_dir(voice_id: str) -> Path:
    # voice_id is generated by us (hex) -> safe, but guard anyway.
    if not voice_id or "/" in voice_id or "\\" in voice_id or ".." in voice_id:
        raise HTTPException(400, "invalid voice_id")
    return VOICES_DIR / voice_id


def _read_meta(voice_id: str) -> dict:
    meta = _voice_dir(voice_id) / "meta.json"
    if not meta.exists():
        raise HTTPException(404, f"voice '{voice_id}' not found")
    return json.loads(meta.read_text())


def _list_voices() -> list[dict]:
    out = []
    for d in sorted(VOICES_DIR.iterdir()):
        m = d / "meta.json"
        if m.is_file():
            try:
                out.append(json.loads(m.read_text()))
            except Exception:
                pass
    return out


# ---- models ------------------------------------------------------------------
class TTSRequest(BaseModel):
    text: str
    voice_id: str
    model: str = DEFAULT_MODEL  # "qwen3" | "omnivoice"
    language: str | None = None  # qwen3: English/Chinese/Auto...; omnivoice: en/zh...
    instruct: str | None = None  # omnivoice voice-design hint (optional)
    max_new_tokens: int = 2048


# ---- routes ------------------------------------------------------------------
@app.get("/")
def root():
    return {
        "service": "vllm-omni unified TTS (voice-cloning)",
        "models": list(WORKERS),
        "default_model": DEFAULT_MODEL,
        "workflow": [
            "POST /voices (multipart audio_sample=@clip.wav, ref_text=..., name=...) -> {voice_id}",
            "POST /tts {text, voice_id, model} -> audio/wav",
        ],
        "endpoints": ["GET /health", "POST /voices", "GET /voices",
                      "GET /voices/{id}", "DELETE /voices/{id}", "POST /tts"],
    }


@app.get("/health")
async def health():
    workers = {}
    async with httpx.AsyncClient(timeout=5.0) as client:
        for name, url in WORKERS.items():
            try:
                r = await client.get(f"{url}/health")
                workers[name] = r.json()
            except Exception as e:
                workers[name] = {"ready": False, "error": repr(e)}
    return {
        "gateway": "ok",
        "voices_registered": len(_list_voices()),
        "workers": workers,
    }


@app.post("/voices")
async def create_voice(
    audio_sample: UploadFile = File(..., description="reference clip (wav/mp3/flac)"),
    ref_text: str = Form(..., description="exact transcript of the reference clip"),
    name: str = Form("", description="optional friendly name"),
):
    raw = await audio_sample.read()
    if not raw:
        raise HTTPException(400, "empty upload")

    voice_id = uuid.uuid4().hex[:12]
    vdir = _voice_dir(voice_id)
    vdir.mkdir(parents=True, exist_ok=True)

    # Normalize to a mono WAV so both engines read it identically.
    src = vdir / f"upload_{audio_sample.filename or 'clip'}"
    src.write_bytes(raw)
    clip = vdir / "clip.wav"
    try:
        data, sr = sf.read(str(src), dtype="float32", always_2d=True)
        mono = data.mean(axis=1)
        sf.write(str(clip), mono, sr, format="WAV", subtype="PCM_16")
        duration = len(mono) / sr
    except Exception as e:
        # leave the raw file; clean dir on hard failure
        raise HTTPException(400, f"could not decode audio: {e!r}")
    finally:
        src.unlink(missing_ok=True)

    meta = {
        "voice_id": voice_id,
        "name": name or voice_id,
        "ref_text": ref_text,
        "clip_path": str(clip),
        "sample_rate": int(sr),
        "duration_sec": round(float(duration), 2),
        "created": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    (vdir / "meta.json").write_text(json.dumps(meta, indent=2))
    if not (1.0 <= duration <= 40.0):
        meta["warning"] = (
            f"reference is {duration:.1f}s; 3-30s clean speech clones best"
        )
    return JSONResponse(meta)


@app.get("/voices")
def list_voices():
    return {"voices": _list_voices()}


@app.get("/voices/{voice_id}")
def get_voice(voice_id: str):
    return _read_meta(voice_id)


@app.delete("/voices/{voice_id}")
def delete_voice(voice_id: str):
    vdir = _voice_dir(voice_id)
    if not vdir.exists():
        raise HTTPException(404, f"voice '{voice_id}' not found")
    for p in vdir.iterdir():
        p.unlink(missing_ok=True)
    vdir.rmdir()
    return {"deleted": voice_id}


@app.post("/tts")
async def tts(req: TTSRequest):
    if req.model not in WORKERS:
        raise HTTPException(400, f"unknown model '{req.model}'; choose {list(WORKERS)}")
    if not req.text or not req.text.strip():
        raise HTTPException(400, "text is required")

    meta = _read_meta(req.voice_id)
    payload = {
        "text": req.text,
        "ref_audio": meta["clip_path"],
        "ref_text": meta.get("ref_text", ""),
        "language": req.language,
        "instruct": req.instruct,
        "max_new_tokens": req.max_new_tokens,
    }
    url = WORKERS[req.model]
    try:
        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
            r = await client.post(f"{url}/infer", json=payload)
    except Exception as e:
        raise HTTPException(502, f"worker '{req.model}' unreachable: {e!r}")
    if r.status_code != 200:
        raise HTTPException(r.status_code, f"worker '{req.model}': {r.text}")
    return Response(
        content=r.content,
        media_type="audio/wav",
        headers={
            "X-Model": req.model,
            "X-Voice-Id": req.voice_id,
            "X-Sample-Rate": r.headers.get("X-Sample-Rate", ""),
            "X-Duration-Sec": r.headers.get("X-Duration-Sec", ""),
            "X-Gen-Sec": r.headers.get("X-Gen-Sec", ""),
        },
    )


def main():
    host = os.environ.get("TTS_GATEWAY_HOST", "0.0.0.0")
    port = int(os.environ.get("TTS_GATEWAY_PORT", "8000"))
    uvicorn.run(app, host=host, port=port, log_level="info")


if __name__ == "__main__":
    main()
